Repository term-world/term-util, pull requests merged in 2023-05, with the labels that each got.

#69 Establishing notary
  libs/notary/src/signer.py
  libs/notary/src/verifier.py
Labels: enhancement

#86 Fixing base template
  libs/inventory/inventory/Item.py
  libs/inventory/inventory/Template.py
Labels: bug

#88 Narrator Changes
  libs/narrator/.paths.yml
  libs/narrator/Demo.py
  libs/narrator/narrator/Narrator.py
  libs/narrator/narrator/Path.py
  libs/narrator/narrator/Question.py
Labels: bug, enhancement

#71 Create download interface for `marketplace`
  libs/couchsurf/couchsurf/request.py
  libs/marketplace/marketplace/listing.py
  libs/marketplace/marketplace/packager.py
  libs/marketplace/marketplace/record.py
  libs/marketplace/marketplace/search.py
  libs/marketplace/setup.py
Labels: bug, enhancement
